from typing import Any, Protocol


class TelegramGateway(Protocol):
    async def create_group(self, title: str, users: list[str]) -> dict[str, Any]: ...

    async def create_channel(self, title: str, about: str, broadcast: bool) -> dict[str, Any]: ...

    async def update_entity(
        self, target: str, title: str | None, about: str | None
    ) -> dict[str, Any]: ...

    async def send_message(self, target: str, message: str) -> dict[str, Any]: ...

    async def resolve_target(self, target: str) -> dict[str, Any]: ...
