from typing import Any, Protocol


class TelegramGateway(Protocol):
    """Contract every Telegram adapter (real or fake) implements.

    Each method corresponds to exactly one workflow action. Add a new action
    by extending this protocol, the ``ActionType`` literal, and every
    implementation together.
    """

    async def create_group(self, title: str, users: list[str]) -> dict[str, Any]: ...

    async def create_channel(self, title: str, about: str, broadcast: bool) -> dict[str, Any]: ...

    async def update_entity(
        self, target: str, title: str | None, about: str | None
    ) -> dict[str, Any]: ...

    async def send_message(self, target: str, message: str) -> dict[str, Any]: ...

    async def resolve_target(self, target: str) -> dict[str, Any]: ...

    async def pin_message(self, target: str, message_id: int) -> dict[str, Any]: ...

    async def unpin_message(self, target: str, message_id: int | None = None) -> dict[str, Any]: ...

    async def edit_message(self, target: str, message_id: int, text: str) -> dict[str, Any]: ...

    async def delete_message(self, target: str, message_id: int) -> dict[str, Any]: ...

    async def forward_message(
        self, from_target: str, to_target: str, message_id: int
    ) -> dict[str, Any]: ...

    async def reply_message(
        self, target: str, reply_to_message_id: int, message: str
    ) -> dict[str, Any]: ...

    async def mark_read(self, target: str) -> dict[str, Any]: ...

    async def archive_chat(self, target: str) -> dict[str, Any]: ...
